import OpenAI from "openai";
import dotenv from "dotenv";
dotenv.config();

const openai = new OpenAI({
  apiKey: process.env.GROQ_API_KEY,
  baseURL: "https://api.groq.com/openai/v1",
});

class GrokService {
  constructor() {
    this.openai = openai;
  }

  async analyzeResume(resume, jobDescription) {
    const prompt = `
    You are an expert resume analyzer and a professional HTML/CSS UI designer.
    
    🎯 OBJECTIVE:
    - Analyze the given resume against the provided job description.
    - Output a fully self-contained, professionally styled HTML5 report.
    - Do NOT fabricate information — keep content strictly derived from resume and job description.
    
    📄 OUTPUT FORMAT:
    - Return a standalone, valid HTML5 document.
    - Must include: <!DOCTYPE html>, <html>, <head>, <style>, <body>.
    - DO NOT return any extra text such as “Here is the resume”, “Below is the HTML”, or any markdown syntax like \`\`\`.
    - Output must begin directly with <!DOCTYPE html> and end with </html> — no explanations before or after.
    
    🎨 GLOBAL DESIGN RULES:
    - Font: "Segoe UI", Helvetica, Arial, sans-serif
    - Background: #f9f9f9
    - Main container:
      - max-width: 1000px
      - margin: 40px auto
      - padding: 30px
      - background: #ffffff
      - box-shadow: 0 0 10px rgba(0, 0, 0, 0.1)
    
    📐 LAYOUT & STRUCTURE:
    - Use single-column layout
    - Stack all sections vertically
    - Wrap each section in a <section> tag with:
      - margin-bottom: 2rem
      - padding: 0.5rem
    
    📋 SECTION HEADINGS:
    - Each section heading must be an <h3> with a 📋 icon (or button) aligned to the right
    - When the 📋 icon is clicked, it must copy that section’s content to the clipboard
    - Section heading style:
      - font-size: 1.2rem
      - font-weight: bold
      - text-transform: uppercase
      - color: #333
      - display: flex
      - justify-content: space-between
      - align-items: center
      - border-bottom: 1px solid #ccc
      - padding-bottom: 6px
      - margin-bottom: 0.8rem
    
    📦 SECTIONS TO INCLUDE:
    
    1️⃣ MATCH SCORE
    - Show a score (0–100) based on how well the resume matches the job description
    - In the next line, provide a brief explanation of the score and why it reduced or increased
    - Style: font-size: 1.1rem; color: #000
    
    2️⃣ MISSING SKILLS
    - List skills/keywords present in job description but missing from resume
    - In then next line, provide a brief explanation of why these skills are important for the job or viceversa
    - Use comma-separated format
    - Style: font-size: 1.1rem; color: #000

    3️⃣ SUGGESTIONS TO IMPROVE
    - Provide actionable, concise suggestions to improve the resume if it does not match the job description well
    - And also include suggestions to improve the resume if it matches the job description well
    - Style: font-size: 1.1rem; color: #000
    
    📋 COPY FUNCTIONALITY REQUIREMENT:
    - Include working JavaScript at the bottom of the HTML that enables the 📋 icon to copy the inner text of its parent section to the clipboard.
    - Use a <script> tag within <body> to define this behavior.
    
    📱 RESPONSIVE BEHAVIOR:
    - Layout must remain readable on mobile screens
    - Stack elements vertically for small widths
    
    🚫 STRICT RULES (MANDATORY):
    - No external stylesheets or frameworks
    - No markdown or backtick blocks
    - Do NOT wrap or prefix with "Here is", "Below is", etc.
    - Do NOT generate any content outside the <html> tag
    - Do NOT include explanations, metadata, or comments
    - Maintain consistent layout, spacing, padding, and font size
    - Output must always follow the same structure — no variation between runs
    
    ⚠️ At the bottom of the page, include this disclaimer in small, gray text:
    "This resume analysis was generated by AI and may contain inaccuracies. Please verify before use."
    
    ---
    Resume:
    """${resume}"""
    
    ---
    Job Description:
    """${jobDescription}"""
    `;
    
    
    
  
    const response = await this.openai.chat.completions.create({
      model: "llama3-70b-8192",
      messages: [{ role: "user", content: prompt }],
    });
  
    return response.choices[0].message.content;
  }
  

  async rewriteResume(resume, jobDescription) {
    const prompt = `
    You are a professional resume writer and expert HTML/CSS designer.
    
    🎯 Objective:
    - Rewrite the given resume content to align **perfectly** with the job description.
    - Keep it professional, concise, and **truthful** — do not fabricate any experience or education.
    
    📄 Output Format:
    - Return a **standalone HTML5 page** with complete structure: <html>, <head>, <style>, <body>
    - Include all CSS inside a <style> tag — do NOT use external stylesheets or frameworks
    - Do not include explanations, markdown, or comments — only HTML content
    
    🎨 Global Design Rules:
    - Font-family: Segoe UI, Helvetica, Arial, sans-serif
    - Background: #f9f9f9
    - Main container:
      - max-width: 1000px
      - margin: 40px auto
      - padding: 30px
      - background: #ffffff
      - box-shadow: 0 0 10px rgba(0, 0, 0, 0.1)
    
    📐 Layout:
    - Use one column layout:
    - All sections should be stacked vertically
    - Use <section> for each major part of the resume
    - Each section should have consistent padding of 0.5rem and margin 0.5rem
    - For each section heading use h3 with a 📋 icon to copy content
      -  Section Header Style (applies to all headings like Skills, Summary, etc.):
        - Style:
        - font-size: 1.2rem
        - font-family: "Segoe UI", Helvetica, Arial, sans-serif
        - font-weight: bold
        - text-transform: uppercase
        - color: #333
        - margin-bottom: .8rem
        - padding-bottom: 6px
        - border-bottom: 1px solid #ccc
        - display: flex
        - justify-content: space-between
        - align-items: center
        - border-bottom: 1px solid #ddd

    - If there is a gap horizontally, align horizontally or else vertically
    
    🧷
    
    📋 Copy to Clipboard:
    - Include a 📋 icon (or similar) to the right of each <h2>
    - When clicked, it copies the section content below the heading
    - Icon style:
      - font-size: 14px
      - cursor: pointer
      - padding-left: 8px
    
    📦 Section-by-Section Requirements:
    
    1️⃣ **Contact Information**
    - Format horizontally separated by commas
    - If missing data, include placeholders:
      - "Your Name", "you@example.com", "+1234567890"
    
    2️⃣ **Skills**
    - Format horizontally by commas
    - If skills are missing:
      - Use keywords from job description
      - If no skills in job description, use common industry skills
      - If no skills in resume, infer from job description
    
    3️⃣ **Professional Summary**
    - 3–5 sentence overview
    - Style:
      - line-height: 1.6
      - margin-top: 10px
    
    4️⃣ **Experience**
    - For Each Job Give Margin Bottom of 1rem
    - Each job: 
      - Job title, Company 
        - Style: font-size: 1.1rem, font-weight: bold, color: #333, margin-bottom: 0.3rem
      - Duration:
         - Style: font-size: 0.9rem, color: #666, margin-bottom: 0.3rem
      - Description in <ul> or <p> blocks
    - If none available, infer from resume and job description
    
    5️⃣ **Projects** (if available)
    - For Each Project give Margin Bottom of 1rem
    - Each project:
      - Project title, Description
        - Style: font-size: 1.1rem, font-weight: bold, color: #333, margin-bottom: 0.3rem
      - Duration:
        - Style: font-size: 0.9rem, color: #666, margin-bottom: 0.3rem
      - Description in <ul> or <p> blocks
    - Format like Experience
    - Mention technologies used and outcome if known
    
    6️⃣ **Education**
    - For Each Education give Margin Bottom of 1rem
    - Each education:
      - Degree, Institution, Year
        - Style: font-size: 1.1rem, font-weight: bold, color: #333, margin-bottom: 0.3rem
      - Description in <ul> or <p> blocks
    - If no education available, give placeholder for user to fill in  - "Degree, Institution, Year"   

    7. ** Suggesetions for Improvement:**
    - Provide specific, actionable suggestions to improve the resume
  
    📱 Responsive Behavior:
    - Ensure readability on mobile devices
    - Layout should stack columns on smaller screens
    
    🚫 STRICT FORMAT RULES:(Mandatory)
    - All sections must follow the exact format above — no variation
    - Do not return different layouts on each run
    - Maintain padding, spacing, and color consistency
    - Do not use global styles that can be overridden externally
    - Include a note as it is generated by AI and not a human And it can make mistakes. 
    - Dont render content outside of the <html> tag
    - Do not include any comments, metadata, or explanations in the output
    - Do NOT include any text, headings, or messages like "Here is your resume", "Below is the HTML", etc.
    - Do NOT use backticks, markdown code blocks, or tags like html.
    - ONLY return valid HTML content inside <html>, <head>, <body>, and <style>.
    - Do NOT wrap or prefix the HTML with any commentary or explanation.
 
    
    ---
    Resume:
    """${resume}"""
    
    ---
    Job Description:
    """${jobDescription}"""
    `;
    
    
    
    
    
    
    

    const response = await this.openai.chat.completions.create({
      model: "llama3-70b-8192", // ✅ Correct model name for Groq
      messages: [{ role: "user", content: prompt }],
    });

    return response.choices[0].message.content;
  }
}

export default new GrokService();
